services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - ../config/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=appu
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp

    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - app-network

volumes:
  db_data:
networks:
  app-network: