services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - ../config/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=appu
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp

    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://app.joshisiris.com.np/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - db
      - app
    networks:
      - app-network
  
volumes:
  db_data:
networks:
  app-network: